spring: 
  rabbitmq: 
    host: 127.0.0.1
    port: 5672 
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb+srv://Kenny:verystrongpass@cluster0.tv8s5.azure.mongodb.net/javalab?retryWrites=true&w=majority